float determinant(float **a,float size);
float** cofactor(float** matrix,int size);
float** transpose_cofactor(float** matrix,float** matrix_cofactor,int size);
float** init_matrix(int n_row,int n_col);
void free_matrix(float** matrix, int n_row);
void memset_matrix(float** matrix,int n_row,int n_col);
void diff_matrix_vector(float **vector, float **vector2,int n_row, int n_col, float **C);
void sum_vectors(Matrix *M, int n_matrix, int n_col, float **C);
void sum_matrix(float **m1, float **m2, int n_row, int n_col);
void prod(float** first, float** second, int row1, int row2, int col1, int col2, float** res);
void transpose(float** matrix,int row, int col, float** res);
void print_matrix(float** matrix, int row, int col);
void diff_vector(float **vector, float **vector2, int n_col, float **C);
void mean(float **M, int n_row, int n_col, float **means);